# Project-wide Gradle settings.

# Allocates 4 GB of RAM for the Gradle Daemon process
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Enables parallel execution of tasks (multi-tasking)
org.gradle.parallel=true

# Enables build caching (reuses previous builds)
org.gradle.caching=true

# Enables Configuration Cache (skips configuration phase if unchanged)
org.gradle.configuration-cache=true

# Keeps the Gradle daemon alive for faster subsequent builds
org.gradle.daemon=true

# Enables Kotlin incremental compilation
kotlin.incremental=true
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
